version: 2.1

workflows:
  ci-cd-pipeline:
    jobs:
      - build-and-push:
          context:
            - test  # Spécifiez le context ici
          filters:
            branches:
              only: main
      - deploy:
          context:
            - test  # Spécifiez le context ici
          requires:
            - build-and-push
          filters:
            branches:
              only: main

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24  # Utiliser une version plus récente
      - run:
          name: Build and Push Docker image
          command: |
            # Build Docker image
            docker build -t $HARBOR_URL/circle_ci/app:$CIRCLE_SHA1 .
            docker tag $HARBOR_URL/circle_ci/app:$CIRCLE_SHA1 $HARBOR_URL/circle_ci/app:latest

            # Login to Harbor
            echo "$HARBOR_PASSWORD" | docker login $HARBOR_URL -u $HARBOR_USERNAME --password-stdin

            # Push Docker image to Harbor
            docker push $HARBOR_URL/circle_ci/app:$CIRCLE_SHA1
            docker push $HARBOR_URL/circle_ci/app:latest

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:90L7RxlJraxJkSr/Ww7k7Zh+En8o+kwkzV6oQctlxyA" # Remplacer par votre empreinte
      - run:
          name: Deploy to server
          command: |
            # Créer le script sans utiliser de heredoc
            echo '#!/bin/bash' > deploy.sh
            echo 'echo "$HARBOR_PASSWORD" | docker login $HARBOR_URL -u "$HARBOR_USERNAME" --password-stdin' >> deploy.sh
            echo 'docker pull $HARBOR_URL/circle_ci/app:latest' >> deploy.sh
            echo 'if [ "$(docker ps -aq -f name=nextjs_app)" ]; then' >> deploy.sh
            echo '  docker stop nextjs_app' >> deploy.sh
            echo '  docker rm nextjs_app' >> deploy.sh
            echo 'fi' >> deploy.sh
            echo 'docker run -d --name nextjs_app -p 3001:3001 --restart unless-stopped $HARBOR_URL/circle_ci/app:latest' >> deploy.sh
            echo 'docker image prune -a -f --filter "until=24h"' >> deploy.sh

            # Envoyer le script au serveur
            scp -o StrictHostKeyChecking=no deploy.sh $SSH_USER@$SSH_HOST:/tmp/deploy.sh

            # Exécuter le script
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "chmod +x /tmp/deploy.sh && /tmp/deploy.sh && rm /tmp/deploy.sh"
